IF OBJECT_ID('dbo.PO_PLO', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.PO_PLO (
        PoID INT NOT NULL,
        PloID INT NOT NULL,
        CONSTRAINT PK_PO_PLO PRIMARY KEY (PoID, PloID),
        CONSTRAINT FK_PO_PLO_PO FOREIGN KEY (PoID) REFERENCES dbo.PO(PoID) ON DELETE CASCADE,
        CONSTRAINT FK_PO_PLO_PLO FOREIGN KEY (PloID) REFERENCES dbo.PLO(PloID) ON DELETE CASCADE
    );
END;
