USE TPMS_DB;
GO

IF OBJECT_ID('dbo.ProgramOutcomePLOMapping', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ProgramOutcomePLOMapping (
        PoID INT NOT NULL,
        PloID INT NOT NULL,
        CONSTRAINT PK_ProgramOutcomePLOMapping PRIMARY KEY (PoID, PloID),
        CONSTRAINT FK_POPLO_PO FOREIGN KEY (PoID) REFERENCES dbo.PO(PoID) ON DELETE CASCADE,
        CONSTRAINT FK_POPLO_PLO FOREIGN KEY (PloID) REFERENCES dbo.PLO(PloID) ON DELETE CASCADE
    );
END;
GO
